// rAthena msg_athena.conf
// Message Configuration of char-server
// -----------------------
0: 新手
1: 剑士
2: 法师
3: 弓手
4: 牧师
5: 商人
6: 盗贼
7: 骑士
8: 神父
9: 巫师
10: 铁匠
11: 猎人
12: 刺客
13: 十字军
14: 僧侣
15: 贤者
16: 流氓
17: 炼金术士
18: 吟游诗人
19: 舞者
20: 婚礼
21: 超级新手
22: 枪手
23: 忍者
24: 圣诞节
25: 高级新手
26: 高级剑士
27: 高级魔法师
28: 高级弓手
29: 高级牧师
30: 高级商人
31: 高级盗贼
32: 领主骑士
33: 高级祭司
34: 高级巫师
35: 白smith
//35: Mastersmith //IRO name
36: 狙击手
37: 刺客十字
38: 圣骑士
39: 冠军
40: 教授
//40: Scholar //IRO name
41: 隐士
42: 创造者
//42: Biochemist //IRO Name
43: 小丑
//43: Minstrel //IRO Name
44: 吉普赛人
45: 宝宝新手
46: 宝宝剑士
47: 宝宝魔法师
48: 宝宝弓箭手
49: 宝宝牧师
50: 宝宝商人
51: 宝宝盗贼
52: 宝宝骑士
53: 宝宝祭司
54: 宝宝巫师
55: 宝宝铁匠
56: 宝宝猎人
57: 宝宝刺客
58: 宝宝十字军
59: 宝宝僧侣
60: 宝宝贤者
61: 宝宝流氓
62: 宝宝炼金术士
63: 宝宝吟游诗人
64: 宝宝舞者
65: 超级宝宝
66: 跆拳道
67: 星斗角斗士
68: 灵魂链接者
//79: FREE
//70: FREE
71: 夏天
72: Gangsi
73: 死亡骑士
74: 黑暗收集者
75: 符文骑士
76: 术士
77: 游侠
78: 大主教
79: 机械师
80: 断头台十字军
81: 皇家卫士
82: 巫师
83: 吟游诗人
//83: Maestro //IRO Name
84: 流浪者
85: 武僧
86: 基因师
//86: Geneticist //IRO Name
87: 影之追踪者
88: 宝宝符文骑士
89: 宝宝术士
90: 宝宝游侠
91: 宝宝大主教
92: 宝宝机械师
93: 宝宝断头台十字军
94: 宝宝皇家卫士
95: 宝宝巫师
96: 宝宝吟游诗人
97: 宝宝流浪者
98: 宝宝武僧
99: 宝宝基因师
100: 宝宝影之追踪者
101: 扩展超级新手
102: 扩展超级宝宝
103: 影子
104: 朦胧
105: 韩服
106: 叛乱
107: 啤酒节
108: 召唤师
109: 宝宝召唤师
110: 宝宝忍者
111: 宝宝影子
112: 宝宝朦胧
113: 宝宝跆拳道
114: 宝宝星际角斗士
115: 宝宝灵魂链接者
116: 宝宝枪手
117: 宝宝反叛者
118: 星帝
119: 灵魂收割者
120: 小星帝
121: 小灵魂收割者
122: 龙骑士
123: 大师
124: 影之交叉
125: 大法师
126: 红衣主教
127: 风鹰
128: 帝国卫队
129: 生物学家
130: 深渊追逐者
131: 元素大师
132: 审判者
133: 吟游诗人
134: 吟唱者
135: 天空皇帝
136: 灵魂修行者
137: 神启
138: 不知火
139: 夜间守望者
140: 超越新手
141: 灵魂操控者

199: 未知职业

//Auction
200: 拍卖管理员
201: 拍卖
202: 谢谢，您赢得了拍卖！
203: 您的拍卖付款！
204: 未找到买家。
205: 拍卖已取消。
206: 拍卖已结束。
207: 拍卖赢家。
208: 有人出价更高。
209: 您已出价更高。
210: 您赢得了拍卖。
211: 您的拍卖付款！

// @accountinfo
212: 未找到符合您条件的项目，'%s'。
213: 发生错误，请联系管理员。
214: 您的查询返回了 %d 个结果，请更具体一些...
215: [AID: %d] %s | %s | 等级: %d/%d | %s
216: 未找到 ID 为 '%d' 的账户。
217: -- 账户 %d --
218: 用户: %s | GM 组: %d | 状态: %d
//219: FREE
//220: FREE
221: 账户邮箱: %s | 出生日期: %s
222: 最后 IP: %s (%s)
223: 该用户已登录 %d 次，最后一次登录时间为 %s
224: -- 角色详情 --
225: [槽位/CID: %d/%d] %s | %s | 等级: %d/%d | %s
226: 该账户没有角色。

// Achievements
227: GM
228: 成就奖励邮件
229: [%s] 成就奖励。
