// rAthena msg_athena.conf
// Message Configuration of login-server
// -----------------------
0: 未注册的 ID。
1: 密码错误。
2: 账户已过期。
3: 被服务器拒绝。
4: 被GM封锁。
5: 游戏EXE版本过旧。
6: 已被禁用。
7: 服务器过载。
8: 公司账户限制。
9: 被DBA禁用。
10: 邮箱未确认。
11: 被GM禁用。
12: 正在数据库中工作。
13: 自我锁定。
14: 不允许的组别。
15: 不允许的组别。
16: 账户不存在。
17: 登录信息仍然存在。
18: 正在进行黑客调查。
19: 正在进行漏洞调查。
20: 正在删除角色。
21: 正在删除配偶角色。
22: 未知错误。
